server:
  port: 18080
### 本地开发环境下的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coal_trading_platform_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 300ms
    key:
      user: 'a:user'
      auth: 'a:auth'
    expire:
      common: 86400 #24小时

